// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MyApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "Smartphones",
                            Description = "Latest Apple flagship phone",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsAvailable = true,
                            Name = "iPhone 15 Pro",
                            Price = 999m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            Category = "Smartphones",
                            Description = "Latest Samsung flagship phone",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsAvailable = true,
                            Name = "Samsung Galaxy S24",
                            Price = 899m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Xiaomi",
                            Category = "Smartphones",
                            Description = "Latest Xiaomi flagship phone",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsAvailable = true,
                            Name = "Xiaomi 14",
                            Price = 699m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("MyApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@store.com",
                            FullName = "Admin User",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@store.com",
                            FullName = "John Doe",
                            Password = "customer123",
                            Role = "Customer",
                            Username = "customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
